import { Station, StationStatus } from './types';

export const MOCK_STATIONS: Station[] = [
  {
    id: '1',
    hostName: 'Rahul Verma',
    title: 'Verma Villa Green Spot',
    location: 'Koregaon Park, Pune',
    rating: 4.8,
    reviewCount: 34,
    pricePerHour: 150,
    status: StationStatus.AVAILABLE,
    image: 'https://picsum.photos/400/300?random=1',
    connectorType: 'Type 2',
    powerOutput: '7.2kW',
    description: 'Secure driveway charger. Covered parking available while charging. Near German Bakery.',
    coords: { x: 40, y: 30 },
    lat: 18.5362,
    lng: 73.8940,
    distance: '0.8 km',
    phoneNumber: '+919876543210'
  },
  {
    id: '2',
    hostName: 'Priya Reddy',
    title: 'TechPark Quick Charge',
    location: 'Hinjewadi Phase 1, Pune',
    rating: 4.5,
    reviewCount: 120,
    pricePerHour: 200,
    status: StationStatus.BUSY,
    image: 'https://picsum.photos/400/300?random=2',
    connectorType: 'CCS2',
    powerOutput: '22kW',
    description: 'Fast DC charging near Wipro Circle. 24/7 access for IT park employees.',
    coords: { x: 60, y: 55 },
    lat: 18.5913,
    lng: 73.7389,
    distance: '12 km',
    phoneNumber: '+919876543211'
  },
  {
    id: '3',
    hostName: 'Amit Singh',
    title: 'Baner High Street Point',
    location: 'Baner, Pune',
    rating: 4.9,
    reviewCount: 12,
    pricePerHour: 120,
    status: StationStatus.AVAILABLE,
    image: 'https://picsum.photos/400/300?random=3',
    connectorType: 'Type 2',
    powerOutput: '3.3kW',
    description: 'Slow charging perfect for evening visits to High Street restaurants.',
    coords: { x: 25, y: 70 },
    lat: 18.5590,
    lng: 73.7868,
    distance: '5.1 km',
    phoneNumber: '+919876543212'
  },
  {
    id: '4',
    hostName: 'Sneha Gupta',
    title: 'FC Road Rapid Point',
    location: 'FC Road, Pune',
    rating: 4.2,
    reviewCount: 8,
    pricePerHour: 250,
    status: StationStatus.OFFLINE,
    image: 'https://picsum.photos/400/300?random=4',
    connectorType: 'Type 2',
    powerOutput: '11kW',
    description: 'Centrally located near Fergusson College. Currently maintenance in progress.',
    coords: { x: 75, y: 20 },
    lat: 18.5196,
    lng: 73.8433,
    distance: '3.2 km',
    phoneNumber: '+919876543213'
  },
  {
    id: '5',
    hostName: 'Vikram Malhotra',
    title: 'Viman Nagar EV Hub',
    location: 'Viman Nagar, Pune',
    rating: 4.7,
    reviewCount: 45,
    pricePerHour: 180,
    status: StationStatus.AVAILABLE,
    image: 'https://picsum.photos/400/300?random=5',
    connectorType: 'CCS2',
    powerOutput: '25kW',
    description: 'High speed charger near Pune Airport. Lounge access available while charging.',
    coords: { x: 0, y: 0 },
    lat: 18.5679,
    lng: 73.9143,
    distance: '4.5 km',
    phoneNumber: '+919876543214'
  },
  {
    id: '6',
    hostName: 'Anjali Deshmukh',
    title: 'Kothrud Power Station',
    location: 'Kothrud, Pune',
    rating: 4.3,
    reviewCount: 22,
    pricePerHour: 140,
    status: StationStatus.BUSY,
    image: 'https://picsum.photos/400/300?random=6',
    connectorType: 'Type 2',
    powerOutput: '7.2kW',
    description: 'Residential charger in prime Kothrud area. Easy access from Karve Road.',
    coords: { x: 0, y: 0 },
    lat: 18.5074,
    lng: 73.8077,
    distance: '6.2 km',
    phoneNumber: '+919876543215'
  },
  {
    id: '7',
    hostName: 'CyberCity Charges',
    title: 'Magarpatta Fast Charge',
    location: 'Magarpatta, Pune',
    rating: 4.6,
    reviewCount: 89,
    pricePerHour: 220,
    status: StationStatus.AVAILABLE,
    image: 'https://picsum.photos/400/300?random=7',
    connectorType: 'CCS2',
    powerOutput: '50kW',
    description: 'Ultra-fast charging inside Magarpatta City. Coffee shop nearby.',
    coords: { x: 0, y: 0 },
    lat: 18.5137,
    lng: 73.9274,
    distance: '8.1 km',
    phoneNumber: '+919876543216'
  },
  {
    id: '8',
    hostName: 'Sanjay Plaza',
    title: 'Aundh Community Point',
    location: 'Aundh, Pune',
    rating: 4.0,
    reviewCount: 15,
    pricePerHour: 100,
    status: StationStatus.AVAILABLE,
    image: 'https://picsum.photos/400/300?random=8',
    connectorType: 'Type 2',
    powerOutput: '3.3kW',
    description: 'Budget friendly charging option. Gated society.',
    coords: { x: 0, y: 0 },
    lat: 18.5635,
    lng: 73.8070,
    distance: '7.5 km',
    phoneNumber: '+919876543217'
  }
];

export const MOCK_HOST_STATS = {
  totalEarnings: 12450,
  activeBookings: 2,
  stationHealth: 98
};

export const INITIAL_USER_AVATAR = "https://picsum.photos/100/100?random=99";